In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [3]:
df = pd.read_csv('iris.csv')
df.head(100)

    sepal.length  sepal.width  petal.length  petal.width     variety
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            4.6          3.1           1.5          0.2      Setosa
4            5.0          3.6           1.4          0.2      Setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  Versicolor
96           5.7          2.9           4.2          1.3  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
98           5.1          2.5           3.0          1.1  Versicolor
99           5.7          2.8           4.1          1.3  Versicolor

[100 rows x 5 columns]

In [4]:
df['Class'] = df['variety'].map(
{
    'Setosa' : 0,
    'Versicolor' : 1,
    'Virginica' : 2
    
})

In [7]:
X = df[['sepal.length', 'sepal.width', 'petal.length', 'petal.width']]
print(X)
Y = df[['Class']]
print(Y)

     sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]
     Class
0        0
1        0
2        0
3        0
4        0
..     ...
145      2
146      2
147      2
148      2
149      2

[150 rows x 1 columns]

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)
id3 = DecisionTreeClassifier(criterion = 'entropy')
cart = DecisionTreeClassifier(criterion = 'gini')